name: build_cuda

on:
  push:
    paths:
      - .github/workflows/build_cuda.yml
  workflow_dispatch: {}

env:
  gmxversion: "2025.3"
  gmxcompileto: C:/FOSS/gromacs_253
  fftwversion: "3.3.10"
  fftwcompileto: C:/FOSS/fftw3

jobs:
  build:
    runs-on: windows-2025
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Install OpenBLAS and hwloc
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Name FOSS -Path C:\
          New-Item -ItemType Directory -Name OpenBLAS -Path C:\FOSS
          Set-Location C:\FOSS\OpenBLAS
          vcpkg new --application
          vcpkg add port openblas[threads]
          vcpkg add port hwloc
          vcpkg install

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.24
        with:
          cuda: "12.8.1"
      
      - name: Copy BuildCustomizations
        shell: pwsh
        run: |
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\" -Force
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\" -Force

      - name: Download Gromacs and FFTW
        shell: bash
        env:
          gmxdownloadlink: https://ftp.gromacs.org/gromacs/gromacs-2025.3.tar.gz
          gmxmd5hash: "5a2315b6f6e13b091bbbbfddee9eb62b"
          fftwlink: https://fftw.org/fftw-3.3.10.tar.gz
          fftwmd5hash: "8ccbf6a5ea78a16dbc3e1306e234cc5c"
        run: |
          curl -Lfo gromacs_src.tar.gz ${{ env.gmxdownloadlink }}
          echo "${{ env.gmxmd5hash }}  gromacs_src.tar.gz" | md5sum -c
          tar xf gromacs_src.tar.gz
          curl -Lfo fftw_src.tar.gz ${{ env.fftwlink }}
          echo "${{ env.fftwmd5hash }}  fftw_src.tar.gz" | md5sum -c
          tar xf fftw_src.tar.gz

      - name: Compile FFTW single precision
        shell: pwsh
        run: |
          Set-Location fftw-${{ env.fftwversion }} 
          New-Item -ItemType Directory -Name build
          Set-Location build
          cmake .. "-DCMAKE_INSTALL_PREFIX=${{ env.fftwcompileto }}" "-DENABLE_AVX=ON" "-DENABLE_AVX2=ON" "-DENABLE_SSE2=ON" "-DENABLE_THREADS=ON" "-DWITH_COMBINED_THREADS=ON" "-DENABLE_FLOAT=ON" "-DBUILD_SHARED_LIBS=ON" -G "Visual Studio 17 2022" -A "x64"
          cmake --build . --target INSTALL --config Release -- "-maxCpuCount" "-p:CL_MPCount=3"
          Set-Location ..\..
          Remove-Item -Path fftw-${{ env.fftwversion }} -Force -Recurse

      - name: Compile GROMACS CUDA
        shell: pwsh
        run: |
          Set-Location gromacs-${{ env.gmxversion }}
          New-Item -ItemType Directory -Name build
          Set-Location build
          cmake .. "-DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }}" "-DCMAKE_PREFIX_PATH=${{ env.fftwcompileto }};C:/FOSS/OpenBLAS/vcpkg_installed/x64-windows" "-DGMX_SIMD=AVX2_256" "-DGMX_GPU=CUDA" "-DGMX_HWLOC=ON" -G "Visual Studio 17 2022" -A "x64"
          cmake --build . --target INSTALL --config Release -- "-maxCpuCount" "-p:CL_MPCount=3"
          Set-Location ..\..
          Remove-Item -Path gromacs-${{ env.gmxversion }} -Force -Recurse

      - name: Checksum
        shell: bash
        run: |
          cd `cygpath "${{ env.gmxcompileto }}"/bin`
          sha256sum gmx.exe | tee gmx.exe.sha256

      - name: Extra force fields
        shell: bash
        run: |
          cd `cygpath "${{ env.gmxcompileto }}"/share/gromacs/top`
          curl -Lf 'https://mackerell.umaryland.edu/download.php?filename=CHARMM_ff_params_files/charmm36-jul2022.ff.tgz' | tar -x --ungzip
          sed -i '1cCHARMM36 all-atom force field (July 2022)' charmm36-jul2022.ff/forcefield.doc
          curl -Lf 'https://mackerell.umaryland.edu/download.php?filename=CHARMM_ff_params_files/charmm36_ljpme-jul2022.ff.tgz' | tar -x --ungzip
          sed -i '1cCHARMM36 LJ-PME all-atom force field (July 2022)' charmm36_ljpme-jul2022.ff/forcefield.doc

      - name: Copy DLLs and Test
        shell: pwsh
        run: |
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\bin\cufft64_*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Copy-Item -Path "${{ env.fftwcompileto }}\bin\*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Copy-Item -Path C:\FOSS\OpenBLAS\vcpkg_installed\x64-windows\bin\*.dll -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Set-Location ${{ env.gmxcompileto }}\bin
          .\gmx.exe -version

      - name: Upload Firmwares
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: GROMACS-${{ env.gmxversion }}_GPU_Windows-AMD64-AVX2_CUDA1281_msvc
          path: ${{ env.gmxcompileto }}
