name: build_cuda

on:
  push:
    paths:
      - .github/workflows/build_cuda.yml
  workflow_dispatch: {}

env:
  gmxversion: "2024.4"
  gmxcompileto: C:\FOSS\gromacs_244
  fftwversion: "3.3.10"
  fftwcompileto: C:\FOSS\fftw3

jobs:
  build:
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Install OpenBLAS
        shell: pwsh
        env:
          VCPKG_PLATFORM_TOOLSET: "v142"
        run: |
          New-Item -ItemType Directory -Name FOSS -Path C:\
          New-Item -ItemType Directory -Name OpenBLAS -Path C:\FOSS
          Set-Location C:\FOSS\OpenBLAS
          vcpkg new --application
          vcpkg add port openblas[threads]
          vcpkg install

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.18
        with:
          cuda: "12.4.1"
      
      - name: Copy BuildCustomizations
        shell: pwsh
        run: |
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\" -Force
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\" -Force

      - name: Download Gromacs and FFTW
        shell: bash
        env:
          gmxdownloadlink: https://ftp.gromacs.org/gromacs/gromacs-2024.4.tar.gz
          gmxmd5hash: "1ce06e1e330c7232e691c3cd7581aa75"
          fftwlink: https://fftw.org/fftw-3.3.10.tar.gz
          fftwmd5hash: "8ccbf6a5ea78a16dbc3e1306e234cc5c"
        run: |
          curl -Lfo gromacs_src.tar.gz ${{ env.gmxdownloadlink }}
          echo "${{ env.gmxmd5hash }}  gromacs_src.tar.gz" | md5sum -c
          tar xf gromacs_src.tar.gz
          curl -Lfo "gromacs-${{ env.gmxversion }}/cmake/gmxManageNvccConfig.cmake" 'https://github.com/KaneGreen/GROMACS-Windows-Builder/raw/refs/heads/master/cmake/gmxManageNvccConfig.cmake'
          sed -i '/gmxManageCcache/aset(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")' "gromacs-${{ env.gmxversion }}/CMakeLists.txt"
          curl -Lfo fftw_src.tar.gz ${{ env.fftwlink }}
          echo "${{ env.fftwmd5hash }}  fftw_src.tar.gz" | md5sum -c
          tar xf fftw_src.tar.gz

      - name: Compile FFTW single precision
        shell: pwsh
        run: |
          Set-Location fftw-${{ env.fftwversion }} 
          New-Item -ItemType Directory -Name build
          Set-Location build
          cmake .. "-DCMAKE_INSTALL_PREFIX=${{ env.fftwcompileto }}" "-DENABLE_AVX=ON" "-DENABLE_AVX2=ON" "-DENABLE_SSE2=ON" "-DENABLE_THREADS=ON" "-DWITH_COMBINED_THREADS=ON" "-DENABLE_FLOAT=ON" "-DBUILD_SHARED_LIBS=ON" -G "Visual Studio 17 2022" -T "v142" -A "x64"
          cmake --build . --target INSTALL --config Release -- "-maxCpuCount" "-p:CL_MPCount=3"
          Set-Location ..\..
          Remove-Item -Path fftw-${{ env.fftwversion }} -Force -Recurse

      - name: Compile GROMACS CUDA
        shell: pwsh
        run: |
          Set-Location gromacs-${{ env.gmxversion }}
          New-Item -ItemType Directory -Name build
          Set-Location build
          cmake .. "-DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }}" "-DCMAKE_PREFIX_PATH=${{ env.fftwcompileto }};C:\FOSS\OpenBLAS\vcpkg_installed\x64-windows" "-DGMX_SIMD=AVX2_256" "-DGMX_GPU=CUDA" -G "Visual Studio 17 2022" -T "v142" -A "x64"
          cmake --build . --target INSTALL --config Release -- "-maxCpuCount" "-p:CL_MPCount=3"
          Set-Location ..\..
          Remove-Item -Path gromacs-${{ env.gmxversion }} -Force -Recurse

      - name: Copy DLLs
        shell: pwsh
        run: |
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\bin\cufft64_*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Copy-Item -Path "${{ env.fftwcompileto }}\bin\*.dll" -Destination "${{ env.gmxcompileto }}\bin\" -Force
          Copy-Item -Path C:\FOSS\OpenBLAS\vcpkg_installed\x64-windows\bin\*.dll -Destination "${{ env.gmxcompileto }}\bin\" -Force

      - name: Show DLLs
        shell: bash
        run: |
          cd /c/FOSS/gromacs_244/bin
          ldd gmx*.exe

      - name: Upload Firmwares
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: GROMACS-${{ env.gmxversion }}_windows-amd64_AVX2_CUDA1241_fftw3_msvc142
          path: ${{ env.gmxcompileto }}
